id: AAA4934A8
base_file: f440B.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:13:50.271358
  last_modified_at: 2022-06-05 20:13:50.271386
